pipeline:
  # PUSHES
  build-platform:
    group: build
    image: astronomerio/ap-build:0.0.2
    commands:
      - make build-platform
    environment:
      - ASTRONOMER_VERSION=${DRONE_COMMIT_SHA:0:8}
      - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: master

  build-airflow:
    group: build
    image: astronomerio/ap-build:0.0.2
    commands:
      - make build-airflow
    environment:
      - ASTRONOMER_VERSION=${DRONE_COMMIT_SHA:0:8}
      - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: master

  # push-platform:
  #   group: push
  #   image: astronomerio/ap-build:0.0.2
  #   commands:
  #     - make push-platform
  #   environment:
  #     - ASTRONOMER_VERSION=${DRONE_COMMIT_SHA:0:8}
  #     - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   when:
  #     branch: master

  # push-airflow:
  #   group: push
  #   image: astronomerio/ap-build:0.0.2
  #   commands:
  #     - make push-airflow
  #   environment:
  #     - ASTRONOMER_VERSION=${DRONE_COMMIT_SHA:0:8}
  #     - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   when:
  #     branch: master


  # DEPLOYMENTS
  # build-platform:
  #   group: build
  #   image: astronomerio/ap-build:0.0.2
  #   commands:
  #     - make build-platform
  #   environment:
  #     - ASTRONOMER_VERSION=${DRONE_BUILD_NUMBER}
  #     - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   when:
  #     event: deployment
  #     environment: production

  # build-airflow:
  #   group: build
  #   image: astronomerio/ap-build:0.0.2
  #   commands:
  #     - make build-airflow
  #   environment:
  #     - ASTRONOMER_VERSION=${DRONE_BUILD_NUMBER}
  #     - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   when:
  #     event: deployment
  #     environment: production

  # push-platform:
  #   group: push
  #   image: astronomerio/ap-build:0.0.2
  #   commands:
  #     - make push-platform
  #   environment:
  #     - ASTRONOMER_VERSION=${DRONE_BUILD_NUMBER}
  #     - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   when:
  #     event: deployment
  #     environment: production

  # push-airflow:
  #   group: push
  #   image: astronomerio/ap-build:0.0.2
  #   commands:
  #     - make push-airflow
  #   environment:
  #     - ASTRONOMER_VERSION=${DRONE_BUILD_NUMBER}
  #     - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   when:
  #     event: deployment
  #     environment: production
