pipeline:
  trigger:
    image: plugins/downstream
    server: http://drone.astronomer.io
    fork: true
    token: "$$DRONE_TOKEN"
    repositories:
      - astronomerio/commander
      - astronomerio/db-bootstrapper
      - astronomerio/default-backend
      - astronomerio/houston-api
      - astronomerio/orbit-ui

  build-platform:
    group: build
    image: astronomerio/ap-build:0.0.2
    commands: make build-platform
    environment:
      - ASTRONOMER_VERSION=${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  build-airflow:
    group: build
    image: astronomerio/ap-build:0.0.2
    commands: make build-airflow
    environment:
      - ASTRONOMER_VERSION=${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
