pipeline:
  ##################################
  ## Github pushes - build with SHA
  ###################################
  build-platform-master:
    group: build
    image: astronomerio/ap-build:0.0.6
    commands:
      - make build-platform
    environment:
      - ASTRONOMER_VERSION=${DRONE_COMMIT_SHA:0:8}
      - ASTRONOMER_USE_MASTER=true
      - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push
      branch: master

  build-platform-stable:
    group: build
    image: astronomerio/ap-build:0.0.6
    commands:
      - make build-platform
    environment:
      - ASTRONOMER_VERSION=${DRONE_COMMIT_SHA:0:8}
      - ASTRONOMER_USE_MASTER=false
      - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push
      branch: release-*

  build-airflow:
    group: build
    image: astronomerio/ap-build:0.0.6
    commands:
      - make build-airflow
    environment:
      - ASTRONOMER_VERSION=${DRONE_COMMIT_SHA:0:8}
      - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push
      branch: [ master, release-* ]

  ##################################
  ## Deployment
  ###################################
  build-platform-master:
    group: build
    image: astronomerio/ap-build:0.0.6
    commands:
      - make build-platform
    environment:
      - ASTRONOMER_USE_MASTER=true
      - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: deployment
      branch: master
      environment: production

  build-platform-stable:
    group: build
    image: astronomerio/ap-build:0.0.6
    commands:
      - make build-platform
    environment:
      - ASTRONOMER_USE_MASTER=false
      - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: deployment
      branch: release-*
      environment: production

  build-airflow:
    group: build
    image: astronomerio/ap-build:0.0.6
    commands:
      - make build-airflow
    environment:
      - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: deployment
      branch: [ master, release-* ]
      environment: production

  # push-platform:
  #   group: push
  #   image: astronomerio/ap-build:0.0.6
  #   commands:
  #     - docker login -u $${DOCKER_USERNAME} -p $${DOCKER_PASSWORD}
  #     - make push-platform
  #   environment:
  #     - ASTRONOMER_VERSION=${DRONE_TAG##v}
  #     - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   secrets: [ docker_username, docker_password ]
  #   when:
  #     event: tag
  #     branch: [ master, release-* ]

  # push-airflow:
  #   group: push
  #   image: astronomerio/ap-build:0.0.6
  #   commands:
  #     - docker login -u $${DOCKER_USERNAME} -p $${DOCKER_PASSWORD}
  #     - make push-airflow
  #   environment:
  #     - ASTRONOMER_VERSION=${DRONE_TAG##v}
  #     - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   secrets: [ docker_username, docker_password ]
  #   when:
  #     event: tag
  #     branch: [ master, release-* ]
