pipeline:
  # Build platform from master branches if pushed to master or tagged from master
  build-platform-master:
    group: build
    image: astronomerio/ap-build:0.0.2
    commands:
      - make build-platform
    environment:
      - ASTRONOMER_VERSION=${DRONE_COMMIT_SHA:0:8}
      - ASTRONOMER_USE_MASTER=true
      - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: [ push, tag ]
      branch:
        include: [ master ]

  # Build platform from stable releases if production deployment
  build-platform-stable:
    group: build
    image: astronomerio/ap-build:0.0.2
    commands:
      - make build-platform
    environment:
      - ASTRONOMER_VERSION=${DRONE_COMMIT_SHA:0:8}
      - ASTRONOMER_USE_MASTER=false
      - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: tag
      branch:
        exclude: [ master ]

  # # Always build airflow from stable releases
  # build-airflow:
  #   group: build
  #   image: astronomerio/ap-build:0.0.2
  #   commands:
  #     - make build-airflow
  #   environment:
  #     - ASTRONOMER_VERSION=${DRONE_COMMIT_SHA:0:8}
  #     - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   when:
  #     event: [ push, tag ]
  #     branch: master

  # # Push platform images to dockerhub
  # push-platform:
  #   group: push
  #   image: astronomerio/ap-build:0.0.2
  #   commands:
  #     - docker login -u $${DOCKER_USERNAME} -p $${DOCKER_PASSWORD}
  #     - make push-platform
  #   environment:
  #     - ASTRONOMER_VERSION=${DRONE_COMMIT_SHA:0:8}
  #     - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   secrets: [ docker_username, docker_password ]
  #   when:
  #     event: deployment
  #     environment: [ staging, production ]

  # # Push airflow images to dockerhub
  # push-airflow:
  #   group: push
  #   image: astronomerio/ap-build:0.0.2
  #   commands:
  #     - docker login -u $${DOCKER_USERNAME} -p $${DOCKER_PASSWORD}
  #     - make push-airflow
  #   environment:
  #     - ASTRONOMER_VERSION=${DRONE_COMMIT_SHA:0:8}
  #     - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   secrets: [ docker_username, docker_password ]
  #   when:
  #     event: deployment
  #     environment: [ staging, production ]
