apiVersion: v1
name: astronomer
version: 0.16.4
appVersion: 0.16.4
description: Helm chart to deploy the Astronomer Platform
icon: https://www.astronomer.io/static/iconforLIGHTbackground.svg
keywords:
  - astronomer
