apiVersion: v1
name: astronomer
version: 0.15.2-rc1
appVersion: 0.15.2-rc1
description: Helm chart to deploy the Astronomer Platform
icon: https://www.astronomer.io/static/iconforLIGHTbackground.svg
keywords:
  - astronomer
