# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Astronomer Open Edition
email: humans@astronomer.io
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for building and running Astronomer Open Edition.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://open.astronomer.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# name of the software
name: Astronomer Open Edition

project:
    version: 0.2.1
    download_url: https://github.com/astronomerio/astronomer/releases

license:
    software: Apache License, Version 2.0
    software_url: https://opensource.org/licenses/Apache-2.0

    docs: CC BY 3.0
    docs_url: http://creativecommons.org/licenses/by/3.0/

links:
    header:
      - title: GitHub
        url: https://github.com/astronomerio/astronomer
    footer:
      - title: GitHub
        url: https://github.com/astronomerio/astronomer
      - title: Issues
        url: https://github.com/astronomerio/astronomer/issues?state=open

ui:
    header:
        color1: "#605985"
        color2: "#232229"

social:
    github:
        user: astronomerio
        repo: astronomer
    twitter:
        enabled: false
        via:
        hash:
        account:
    facebook:
        enabled: false
        profileUrl:

analytics:
    google: UA-54102728-7

# Build settings
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock
    - "*.sh"
